export const fileHeader = `// THIS FILE IS AUTO-GENERATED BY PROTO-REQUEST
/* eslint-disable */
"use strict";
`;

export const polyfillFileHeader = `// THIS FILE IS AUTO-GENERATED BY PROTO-REQUEST
/* eslint-disable */`;
